### ISSUE TITLE
undefined reference to `saif::saif_parser::error(std::string const&)'

### ISSUE THREAD

**Issue by Vahhab** [wsong83/cppSaif#1]
I got error during compilation on centos 7.3.
My gcc version is   4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) and My bison version is  3.0.4.
Here is the prompt after running make command:

make bison -C src
make[1]: Entering directory `/home/milad/Desktop/x2/cppSaif-master/src'
bison saif.y
saif.y:4.9-17: warning: deprecated directive, use ‘%define api.namespace saif’ [-Wdeprecated]
 %define namespace "saif"
         ^^^^^^^^^
saif.y:4.9-17: warning: %define variable 'api.namespace' requires '{...}' values [-Wdeprecated]
 %define namespace "saif"
         ^^^^^^^^^
saif.y:5.9-25: warning: %define variable 'parser_class_name' requires '{...}' values [-Wdeprecated]
 %define parser_class_name "saif_parser"
         ^^^^^^^^^^^^^^^^^
make[1]: Leaving directory `/home/milad/Desktop/x2/cppSaif-master/src'
make  -C src
make[1]: Entering directory `/home/milad/Desktop/x2/cppSaif-master/src'
ccache g++ -I. -std=c++0x -Wall -Wextra -g3 -c saif.cc -o saif.o
saif.y:271:38: error: ‘location’ in namespace ‘saif’ does not name a type
 void saif::saif_parser::error (const saif::location& loc, const std::string& msg) {
                                      ^
saif.y:271:54: error: ISO C++ forbids declaration of ‘loc’ with no type [-fpermissive]
 void saif::saif_parser::error (const saif::location& loc, const std::string& msg) {
                                                      ^
saif.y:271:6: error: prototype for ‘void saif::saif_parser::error(const int&, const string&)’ does not match any in class ‘saif::saif_parser’
 void saif::saif_parser::error (const saif::location& loc, const std::string& msg) {
      ^
saif.cc:1010:3: error: candidates are: void saif::saif_parser::error(const saif::saif_parser::syntax_error&)
   saif_parser::error (const syntax_error& yyexc)
   ^
In file included from saif.cc:84:0:
saif.hh:287:18: error:                 virtual void saif::saif_parser::error(const string&)
     virtual void error (const std::string& msg);
                  ^
make[1]: *** [saif.o] Error 1
make[1]: Leaving directory `/home/milad/Desktop/x2/cppSaif-master/src'
make: *** [src] Error 2

**Comment by wsong83** [comment]
Sorry for the long delay.

It seems the definitions for location support is not emitted by default for newer versions of bison.
The easiest fix is to remove the location in error report.
A fix have been pushed through commit 59b6ce5b5f2c6b1b55f6282c6c13a7d3466ae7c5.
